# Generated by Django 3.2.5 on 2021-08-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniTipsApp', '0002_auto_20210804_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'info'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'subjects'},
        ),
    ]
