# Generated by Django 3.2.5 on 2021-08-05 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniTipsApp', '0003_auto_20210804_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='uni_related',
        ),
        migrations.AddField(
            model_name='subjects',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subjects',
            name='on_topic',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subj_content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subj_prof',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
